{% set version = "0.8.0" %}

package:
  name: conda-execute
  version: {{ version }}

source:
  fn: conda-execute-{{ version }}.tar.gz
  url: https://github.com/pelson/conda-execute/archive/v{{ version }}.tar.gz
  sha256: b5e589fec98d91311128acf5413ed48c21db413b046f7f8b3cf32a3a0bac9b76

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - conda-execute = conda_execute.execute:main
    - conda-tmpenv = conda_execute.tmpenv:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyyaml
    - conda >=4.1.0
    - psutil

test:
  imports:
    - conda_execute
  commands:
    - conda execute --help
    - conda tmpenv --help

about:
  home: https://github.com/pelson/conda-execute
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Execute scripts in isolated temporary environments.'

extra:
  recipe-maintainers:
    - pelson
