{% set version = "0.7.0" %}

package:
  name: conda-execute
  version: {{ version }}

source:
  fn: conda-execute-{{ version }}.tar.gz
  url: https://github.com/pelson/conda-execute/archive/v{{ version }}.tar.gz
  sha256: 28fca79cb61d4e54d121aebb09ec4aac7098b94a455333aeef1278e99571de67

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pyyaml
    - conda >=4.1.0
    - psutil

test:
  imports:
    - conda_execute
  commands:
    - conda execute --help
    - conda tmpenv --help

about:
  home: https://github.com/pelson/conda-execute
  license: BSD 3-Clause
  summary: 'Execute scripts in isolated temporary environments.'

extra:
  recipe-maintainers:
    - pelson
