travis:
  secure:
    BINSTAR_TOKEN: OQiOVEavTDUTRBr0s6xyAEPHsTmLsA3lHTGELUsKrplEvYE4E446aGsH2Z+12i1w1AumM28ZoIUBNGHMDNSEKeZsY/2LTvIBGhyoCmHcpRfHE4sZOKk+33sTSnfCsnNHcobMe7ArC+L2Q69rO7yD8SyrYlepP4K/ZJtY/hnK+IzBkRYC/kB9sSTtpkuydLn+AFIpOm+suC4swfSXyQqOO+SJWDMGfnOaYP7jpKw6Pl7ss3b5iEGsRByZoQYgeC3BaMqTCXExg1ac7NxpqYilYNB4bvMBEpZQDuSJT0gB8V8tDHJtilXYQ4Ka5tcbtgNRDEqehABoWzDncdTlfguL3yjx7gDc5pCPtEPoVF14gMWOvZ27qz9nSuuOHpZ0y6ZZvCs7eNyNzFSYPaHuhvry1y/d8+aZJ94rZsRb0WvFts2XGfthzDTgBpKkyki4F/K7EKddLwly36paDJy1cB9ZGG7sgx0HbGhoxgHvXNkAlF33ZRQkqOdESsniVTllkb5Lm4BpNaA1jS8co6h1l2nyvBG5AY6l+NtBqsZWTf46x1tfRfkwF+C9ck5LI06t4jGhHXQRzzIpu/pUvsBNNRSTOTU6723KBqU9alViWL9SN7Dy6FqvfZYOlXmP3vuh2qABg8A5TgYj4/OEWedol/yeKKpYRY6rwYh0X15TO1TUbOA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
